Explicit (empty) result for internal POST endpoints
Add explicit result (HTTP status code 200 + empty JSON response) for
internal POST endpoints. Otherwise the method's return value is added to
the response, e.g. an event object. This causes serialization issues
when using Puma as webserver, such as:

 NoMethodError: undefined method `bytesize' for [:id, 123]:Array