CRUD endpoints for users resource now consider local roles
* Users with space or org roles can now see other users in their orgs
* The following is a rough summary of the commit history for all the
squashed commits from this track of work.

------------------------------------------------------------------------
`GET /v3/users` Lists users, if permitted

The large test in `user_spec.rb` is an rspec-ified version of the Miro
board <https://miro.com/app/board/o9J_kwAiqsc=/>; it's a long test, and
thorough.

We also tested against `user.id` rather than `user.guid`, even though
`user.guid` would have been friendlier to read; we felt it inappropriate
to bend the code to accommodate the tests.

The tests are NOT currently passing.

------------------------------------------------------------------------
WIP: `roles_spec` has proper expectations

User visibility has been implemented, meaning we can test the expected
behavior; previously, we restricted the tests to the most basic (and
incorrect) permissions that we implemented at the time

Per Reid & Supraja:

>  Note: currently, all users except admins are only able to see
themselves, so they all get 422. When we expand the visibility of users,
some will get 403s and some will get 422s.

-----------------------------------------------------------------------
Org users can see **all** other users in org

Affects `GET /v3/users`

Much of this code is simplification: previously we had a much more
granular permissions structure (e.g. a user in a space in an org could
not see users outside its space). Now visibility is determined at the
org level (every user assigned a space role will also have an org role).

Exception: a user could always see themselves even if they weren't a
member of any org.

We removed `visible_users_in_my_spaces`; it no longer had a purpose.

--------------------------------------------------------------------------
🐞 `POST /v3/roles` returns 403 before 422

The prior, incorrect behavior was to return a `422` (unprocessable
entity) error when the correct return was a `403` (forbidden). The cause
was a mis-ordering of error checking in the roles controller.

---------------------------------------------------------------------------
Correctly use permission queryer for user list and show

Previously a change was made to accomodate the global_auditor's
visible users. This commit makes this behavior change more standard by
calling the approriate method rather than in permissions queryer rather
than modifying underlying calls.

Delete and update user endpoints now consider all readable users

This change updates the permissions for the delete and update endpoint
to match the other endpoints. This change also includes a small refactor
to fix the complexity in a roles controller method.

[finishes #168117402]

Co-authored-by: Belinda Liu <bliu@pivotal.io>
Co-authored-by: Brian Cunnie <bcunnie@pivotal.io>
Co-authored-by: Merric de Launey <mdelauney@pivotal.io>
Co-authored-by: Supraja Narasimhan <snarasimhan@pivotal.io>